---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8'

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend:
    - RUN microdnf install gcc python3-devel krb5-devel krb5-workstation python-devel dnf-plugins-core
  append:
    - RUN microdnf config-manager --add-repo https://rpm.releases.hashicorp.com/v1.3.7/hashicorp.repo
    - RUN microdnf install terraform